"""Adapters from upstream GOBLIN animal data to ED pasture-DM controls.

The public GOBLIN package family already uses the same 21 cattle cohort names as
GOBLIN-Spatial.  Sheep animal rows use generic LCA cohort names plus a grazing
label (``flat_pasture`` / ``hilly_pasture``), which this module maps back to the
10 GOBLIN-Spatial sheep cohorts.

This module deliberately uses lazy imports for ``cattle_lca`` and ``sheep_lca``.
The core GOBLIN-Spatial package therefore remains independently installable,
while users who install the optional ``goblin`` extra can derive the exact
pasture dry-matter coefficients used by the upstream GOBLIN animal definitions.

The key contract is a profile:

``cohort -> tonnes pasture dry matter per head per year``

which can be passed directly to ``calculate_spared_grassland``.
"""

from __future__ import annotations

from collections.abc import Mapping
from types import SimpleNamespace
from typing import Any, Protocol

import numpy as np
import pandas as pd

from goblin_spatial.cattle.cohorts import FINAL_21_COHORTS
from goblin_spatial.sheep.cohorts import GOBLIN_SHEEP_10


class GrassFeedProtocol(Protocol):
    """Minimal interface implemented by cattle_lca/sheep_lca GrassFeed."""

    def dry_matter_from_grass(self, animal: Any) -> float: ...


CATTLE_COHORTS = tuple(FINAL_21_COHORTS)
SHEEP_COHORTS = tuple(GOBLIN_SHEEP_10)
ALL_GOBLIN_COHORTS = CATTLE_COHORTS + SHEEP_COHORTS

# livestock_generation.COHORT_NAME_DICT collapses lowland/upland sheep to the
# generic LCA cohort name.  Grazing retains the system through flat_/hilly_.
_SHEEP_GENERIC_TO_SUFFIX = {
    "ewes": "ewes",
    "ram": "ram",
    "lamb_less_1_yr": "lamb_less_1_yr",
    "lamb_more_1_yr": "lamb_more_1_yr",
    "male_less_1_yr": "male_less_1_yr",
}


def _sheep_system_from_grazing(value: object) -> str:
    text = str(value).strip().lower()
    if text.startswith("flat_") or text in {"flat", "lowland", "lowland_pasture"}:
        return "Lowland"
    if text.startswith("hilly_") or text in {"hilly", "upland", "upland_pasture"}:
        return "Upland"
    raise ValueError(
        "cannot distinguish lowland/upland sheep from grazing value "
        f"{value!r}; expected flat_* or hilly_*"
    )


def canonical_goblin_spatial_cohort(row: Mapping[str, object]) -> str:
    """Return the GOBLIN-Spatial 31-cohort name for an upstream animal row."""

    cohort = str(row["cohort"])
    if cohort in CATTLE_COHORTS:
        return cohort
    if cohort in _SHEEP_GENERIC_TO_SUFFIX:
        system = _sheep_system_from_grazing(row.get("grazing"))
        return f"{system} {_SHEEP_GENERIC_TO_SUFFIX[cohort]}"
    if cohort in SHEEP_COHORTS:
        # Accept already-expanded sheep rows too.
        return cohort
    raise ValueError(f"unknown upstream GOBLIN cohort: {cohort!r}")


def _default_feed_classes(ef_country: str) -> tuple[GrassFeedProtocol, GrassFeedProtocol]:
    try:
        from cattle_lca.lca import GrassFeed as CattleGrassFeed
        from sheep_lca.lca import GrassFeed as SheepGrassFeed
    except ImportError as exc:  # pragma: no cover - optional dependency path
        raise ImportError(
            "GOBLIN pasture-DM derivation requires the optional upstream packages. "
            "Install goblin-spatial[goblin] or supply cattle_feed and sheep_feed."
        ) from exc
    return CattleGrassFeed(ef_country), SheepGrassFeed(ef_country)


def pasture_dm_profile_from_goblin_animals(
    animal_dataframe: pd.DataFrame,
    *,
    ef_country: str = "ireland",
    year: int | None = None,
    scenario: int | str | None = None,
    cattle_feed: GrassFeedProtocol | None = None,
    sheep_feed: GrassFeedProtocol | None = None,
    require_all_cohorts: bool = True,
) -> dict[str, float]:
    """Derive GOBLIN pasture-DM/head/year coefficients from animal rows.

    Parameters
    ----------
    animal_dataframe:
        DataFrame generated by ``livestock_generation.AnimalData`` (baseline or
        scenario).  Multiple rows for the same cohort are allowed.  Their
        per-head pasture-DM values are population-weighted, matching the way the
        upstream grassland module aggregates animal demand.
    year, scenario:
        Optional selectors for combined dataframes.
    cattle_feed, sheep_feed:
        Optional injected GrassFeed-compatible calculators.  Supplying these is
        useful for tests; otherwise the public ``cattle_lca`` and ``sheep_lca``
        implementations are imported lazily.
    require_all_cohorts:
        If True, require all 21 cattle and 10 sheep cohort controls.

    Returns
    -------
    dict
        ``cohort -> tonnes pasture DM/head/year``.
    """

    required = {
        "cohort",
        "pop",
        "weight",
        "daily_milk",
        "forage",
        "grazing",
        "con_type",
        "con_amount",
    }
    missing = sorted(required - set(animal_dataframe.columns))
    if missing:
        raise ValueError(f"upstream GOBLIN animal dataframe missing columns: {missing}")

    frame = animal_dataframe.copy()
    if year is not None:
        if "year" not in frame.columns:
            raise ValueError("year selector supplied but animal dataframe has no 'year' column")
        frame = frame.loc[pd.to_numeric(frame["year"], errors="raise").astype(int) == int(year)]
    if scenario is not None:
        if "Scenarios" not in frame.columns:
            raise ValueError(
                "scenario selector supplied but animal dataframe has no 'Scenarios' column"
            )
        frame = frame.loc[frame["Scenarios"].astype(str) == str(scenario)]
    if frame.empty:
        raise ValueError("no upstream GOBLIN animal rows remain after filtering")

    if cattle_feed is None or sheep_feed is None:
        default_cattle, default_sheep = _default_feed_classes(ef_country)
        cattle_feed = cattle_feed or default_cattle
        sheep_feed = sheep_feed or default_sheep

    annual_factor = 365.0e-3  # kg DM/head/day -> t DM/head/year
    values: dict[str, list[float]] = {cohort: [] for cohort in ALL_GOBLIN_COHORTS}
    weights: dict[str, list[float]] = {cohort: [] for cohort in ALL_GOBLIN_COHORTS}

    for _, row in frame.iterrows():
        row_dict = row.to_dict()
        canonical = canonical_goblin_spatial_cohort(row_dict)
        population = float(row_dict["pop"])
        if not np.isfinite(population) or population < 0:
            raise ValueError(f"invalid upstream population for {canonical}: {population}")

        animal = SimpleNamespace(**row_dict)
        feed = cattle_feed if canonical in CATTLE_COHORTS else sheep_feed
        dm_kg_per_head_day = float(feed.dry_matter_from_grass(animal))
        if not np.isfinite(dm_kg_per_head_day) or dm_kg_per_head_day < 0:
            raise ValueError(
                f"invalid upstream pasture DM/head/day for {canonical}: "
                f"{dm_kg_per_head_day}"
            )
        values[canonical].append(dm_kg_per_head_day * annual_factor)
        weights[canonical].append(population)

    profile: dict[str, float] = {}
    for cohort in ALL_GOBLIN_COHORTS:
        cohort_values = np.asarray(values[cohort], dtype=float)
        cohort_weights = np.asarray(weights[cohort], dtype=float)
        if len(cohort_values) == 0:
            if require_all_cohorts:
                raise ValueError(f"upstream GOBLIN animal dataframe has no row for {cohort}")
            continue
        if float(cohort_weights.sum()) > 0:
            profile[cohort] = float(np.average(cohort_values, weights=cohort_weights))
        else:
            # GOBLIN animal generators retain parameter rows for zero-population
            # cohorts.  Their animal attributes still define a valid per-head
            # requirement, so retain the unweighted mean for future support.
            profile[cohort] = float(cohort_values.mean())

    return profile


def pasture_dm_profiles_from_goblin_frames(
    animal_frames_by_year: Mapping[int, pd.DataFrame],
    *,
    ef_country: str = "ireland",
    scenario_by_year: Mapping[int, int | str] | None = None,
    cattle_feed: GrassFeedProtocol | None = None,
    sheep_feed: GrassFeedProtocol | None = None,
) -> dict[int, dict[str, float]]:
    """Build the year-indexed profile contract used by the spared-land engine."""

    profiles: dict[int, dict[str, float]] = {}
    for year, frame in sorted(animal_frames_by_year.items()):
        scenario = None if scenario_by_year is None else scenario_by_year.get(int(year))
        profiles[int(year)] = pasture_dm_profile_from_goblin_animals(
            frame,
            ef_country=ef_country,
            year=int(year) if "year" in frame.columns else None,
            scenario=scenario,
            cattle_feed=cattle_feed,
            sheep_feed=sheep_feed,
        )
    return profiles
